{"uuid": "79a6739b-9aae-40e6-9c7a-cfeb710dd641", "children": ["ed83067c-69a5-4013-b3a9-aa2a6c7ed8b2"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'driver' referenced before assignment\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/zhangxiangkui/Downloads/AutomationTest/testcase/conftest.py\", line 35, in start_appium_desired\n    return driver\n"}, "start": 1587405232876, "stop": 1587405232887}], "start": 1587405232876, "stop": 1587405232945}