{"uuid": "b9aca650-3268-478d-af7d-4fa124385547", "children": ["bde3a4a0-ebaf-4de9-b2bb-f5a686a3d7f5"], "befores": [{"name": "start_appium_desired", "status": "broken", "statusDetails": {"message": "UnboundLocalError: local variable 'driver' referenced before assignment\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/_pytest/fixtures.py\", line 792, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"/Users/zhangxiangkui/Downloads/AutomationTest/testcase/conftest.py\", line 36, in start_appium_desired\n    return driver\n"}, "start": 1587406476339, "stop": 1587406476350}], "start": 1587406476339, "stop": 1587406476406}